spring:
  datasource:
    url: jdbc:h2:mem:storagedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 9001

app:
  admin:
    registration:
      token: "CHANGE_ME_ADMIN_TOKEN"

  s3:
    endpoint: http://minio:9000
    access-key: minioadmin
    secret-key: minioadmin123
    region: us-east-1
    bucket: images
